// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeUFSnmyCm-VTp9qWtgUiRUmuZt0tE-jE',
    appId: '1:676384616860:web:798f4b379c6a1cf1835859',
    messagingSenderId: '676384616860',
    projectId: 'isharaa-559f6',
    authDomain: 'isharaa-559f6.firebaseapp.com',
    storageBucket: 'isharaa-559f6.firebasestorage.app',
    measurementId: 'G-HW5X8M7YV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnuVx5NaMBEdx_hPR1X6tIuSXHjppnaY',
    appId: '1:676384616860:android:a4c8a06e953f3b91835859',
    messagingSenderId: '676384616860',
    projectId: 'isharaa-559f6',
    storageBucket: 'isharaa-559f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHxOD-qVqHde-5xg5s1kD3EAqq1n3jY3M',
    appId: '1:676384616860:ios:81b4a8129ac658ba835859',
    messagingSenderId: '676384616860',
    projectId: 'isharaa-559f6',
    storageBucket: 'isharaa-559f6.firebasestorage.app',
    iosBundleId: 'com.example.ishara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHxOD-qVqHde-5xg5s1kD3EAqq1n3jY3M',
    appId: '1:676384616860:ios:81b4a8129ac658ba835859',
    messagingSenderId: '676384616860',
    projectId: 'isharaa-559f6',
    storageBucket: 'isharaa-559f6.firebasestorage.app',
    iosBundleId: 'com.example.ishara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeUFSnmyCm-VTp9qWtgUiRUmuZt0tE-jE',
    appId: '1:676384616860:web:d1cebbd1e5864940835859',
    messagingSenderId: '676384616860',
    projectId: 'isharaa-559f6',
    authDomain: 'isharaa-559f6.firebaseapp.com',
    storageBucket: 'isharaa-559f6.firebasestorage.app',
    measurementId: 'G-FKZVWEB3J4',
  );
}
